In [87]:
import pandas as pd
df_product = pd.read_csv('Products.csv')
df_product

,ProductKey,ProductName,Brand,Color,UnitCostUSD,UnitPriceUSD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,6.62,12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,6.62,12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,7.40,14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,11.00,21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,11.00,21.57,101,MP4&MP3,1,Audio
...,...,...,...,...,...,...,...,...,...,...
2512,2513,Contoso Bluetooth Active Headphones L15 Red,Contoso,Red,43.07,129.99,505,Cell phones Accessories,5,Cell phones
2513,2514,Contoso Bluetooth Active Headphones L15 White,Contoso,White,43.07,129.99,505,Cell phones Accessories,5,Cell phones
2514,2515,Contoso In-Line Coupler E180 White,Contoso,White,1.71,3.35,505,Cell phones Accessories,5,Cell phones
2515,2516,Contoso In-Line Coupler E180 Black,Contoso,Black,1.71,3.35,505,Cell phones Accessories,5,Cell phones
2516,2517,Contoso In-Line Coupler E180 Silver,Contoso,Silver,1.71,3.35,505,Cell phones Accessories,5,Cell phones

In [88]:
df_sale = pd.read_csv('Sales.csv')
df_sale

,OrderNumber,LineItem,OrderDate,DeliveryDate,CustomerKey,StoreKey,ProductKey,Quantity,CurrencyCode
0,366000,1,1/1/2016,NaN,265598,10,1304,1,CAD
1,366001,1,1/1/2016,1/13/2016,1269051,0,1048,2,USD
2,366001,2,1/1/2016,1/13/2016,1269051,0,2007,1,USD
3,366002,1,1/1/2016,1/12/2016,266019,0,1106,7,CAD
4,366002,2,1/1/2016,1/12/2016,266019,0,373,1,CAD
...,...,...,...,...,...,...,...,...,...
62879,2243030,1,2/20/2021,NaN,1216913,43,632,3,USD
62880,2243031,1,2/20/2021,2/24/2021,511229,0,98,4,EUR
62881,2243032,1,2/20/2021,2/23/2021,331277,0,1613,2,CAD
62882,2243032,2,2/20/2021,2/23/2021,331277,0,1717,2,CAD
62883,2243032,3,2/20/2021,2/23/2021,331277,0,464,7,CAD

In [89]:
df_content_base = pd.read_csv('df_content_base.csv')

In [90]:
df_sale_have_productKey_order = df_sale[df_sale['ProductKey'].isin(df_content_base['ProductKey'])]['OrderNumber']
df_sale_have_productKey = df_sale[df_sale['OrderNumber'].isin(df_sale_have_productKey_order)]
#df_sale_have_productKey
df_sale_have_productKey

,OrderNumber,LineItem,OrderDate,DeliveryDate,CustomerKey,StoreKey,ProductKey,Quantity,CurrencyCode
217,372016,1,1/7/2016,NaN,1170323,42,1581,2,GBP
218,372016,2,1/7/2016,NaN,1170323,42,6,3,GBP
271,374016,1,1/9/2016,NaN,1535357,45,9,5,USD
439,385009,1,1/20/2016,NaN,1720050,61,6,1,USD
440,385009,3,1/20/2016,NaN,1720050,61,123,5,USD
...,...,...,...,...,...,...,...,...,...
62734,2241013,7,2/18/2021,2/22/2021,1259633,0,1680,1,USD
62744,2241016,1,2/18/2021,NaN,1743547,66,7,1,USD
62806,2243000,1,2/20/2021,NaN,723572,30,9,8,EUR
62807,2243000,3,2/20/2021,NaN,723572,30,553,9,EUR
62808,2243000,4,2/20/2021,NaN,723572,30,1322,1,EUR

In [91]:
df_product

,ProductKey,ProductName,Brand,Color,UnitCostUSD,UnitPriceUSD,SubcategoryKey,Subcategory,CategoryKey,Category
0,1,Contoso 512MB MP3 Player E51 Silver,Contoso,Silver,6.62,12.99,101,MP4&MP3,1,Audio
1,2,Contoso 512MB MP3 Player E51 Blue,Contoso,Blue,6.62,12.99,101,MP4&MP3,1,Audio
2,3,Contoso 1G MP3 Player E100 White,Contoso,White,7.40,14.52,101,MP4&MP3,1,Audio
3,4,Contoso 2G MP3 Player E200 Silver,Contoso,Silver,11.00,21.57,101,MP4&MP3,1,Audio
4,5,Contoso 2G MP3 Player E200 Red,Contoso,Red,11.00,21.57,101,MP4&MP3,1,Audio
...,...,...,...,...,...,...,...,...,...,...
2512,2513,Contoso Bluetooth Active Headphones L15 Red,Contoso,Red,43.07,129.99,505,Cell phones Accessories,5,Cell phones
2513,2514,Contoso Bluetooth Active Headphones L15 White,Contoso,White,43.07,129.99,505,Cell phones Accessories,5,Cell phones
2514,2515,Contoso In-Line Coupler E180 White,Contoso,White,1.71,3.35,505,Cell phones Accessories,5,Cell phones
2515,2516,Contoso In-Line Coupler E180 Black,Contoso,Black,1.71,3.35,505,Cell phones Accessories,5,Cell phones
2516,2517,Contoso In-Line Coupler E180 Silver,Contoso,Silver,1.71,3.35,505,Cell phones Accessories,5,Cell phones

In [92]:
# Hàm tính lợi nhuận cho mỗi sản phẩm
def calculate_profit(product_key, quantity):
    product = df_product[df_product['ProductKey'] == product_key]
    if not product.empty:
        unit_profit = product['UnitPriceUSD'].values[0] - product['UnitCostUSD'].values[0]
        return round(unit_profit * quantity)
    else:
        return 0

# Tạo ra dữ liệu DB_Utility (ProductKey : Tổng lợi nhuận : Lợi nhuận của từng ProductKey)
db_utility_data = []

for order_num, group in df_sale_have_productKey.groupby('OrderNumber'):
    product_keys = group['ProductKey'].tolist()
    quantities = group['Quantity'].tolist()

    # Chỉ tiếp tục nếu có từ 2 ProductKey trở lên
    if len(product_keys) >= 2:
        # Tính lợi nhuận cho từng ProductKey
        profits = [calculate_profit(product_key, quantity) for product_key, quantity in zip(product_keys, quantities)]
        
        # Tính tổng lợi nhuận cho cả giao dịch
        total_profit = sum(profits)
        
        # Tạo chuỗi DB_Utility theo định dạng yêu cầu
        utility_entry = f"{' '.join(map(str, product_keys))}:{total_profit}:{' '.join(map(str, profits))}"
        db_utility_data.append(utility_entry)

# Kết quả DB_Utility
db_utility_data

['1581 6:325:293 32',
 '6 123:767:11 756',
 '2355 1209 2:2334:851 1426 57',
 '1599 32 2 2006:702:31 512 19 140',
 '37 535:297:200 97',
 '1223 3:683:676 7',
 '1216 1694 1209 6:3791:2344 10 1426 11',
 '853 3:168:154 14',
 '95 34 56:1022:99 329 594',
 '406 1986 1647 1604 4 171 1590:1304:563 137 97 348 21 107 31',
 '1211 1758 7:1021:918 50 53',
 '2458 150 4:2419:10 2377 32',
 '17 3:102:59 43',
 '14 1660:362:168 194',
 '175 187 2002 1592 6 103 1227:1615:63 174 108 39 11 559 661',
 '4 443 38 143:1700:11 754 200 735',
 '1792 2075 1461 1309 1663 8:1694:105 292 1165 96 7 29',
 '101 34:436:389 47',
 '4 1590 1973:526:53 61 412',
 '1261 1388 3:247:54 143 50',
 '964 423 49 3:676:194 324 108 50',
 '2065 508 140 8:965:98 151 540 176',
 '8 1630 1350:66:29 31 6',
 '947 1629 2:105:89 10 6',
 '62 8 1581 1513:1715:196 59 879 581',
 '1738 3:83:69 14',
 '4 418:153:21 132',
 '2210 8:205:176 29',
 '37 1586:414:400 14',
 '37 2094:979:600 379',
 '1572 1158 2:3399:219 3129 51',
 '1748 417 423 8 57:1550:73 971 324 29 153',
 '2123 1693 69 7:2072:2015 11 25 21',
 '3 430 902 1070 1430:962:7 265 22 506 162',
 '1576 615 94 4:532:6 449 66 11',
 '56 3:1238:1188 50',
 '173 37 1353 2095:3335:132 200 44 2959',
 '187 847 6:279:174 31 74',
 '1537 14:1764:1722 42',
 '2109 34 1780:677:379 235 63',
 '458 1643 429 2 580:1593:113 250 972 13 245',
 '3 58:236:7 229',
 '4 1630:72:11 61',
 '986 14:112:70 42',
 '37 1586:814:800 14',
 '2 978 431 482 1614:949:13 194 181 387 174',
 '449 34:801:754 47',
 '49 34 103:527:324 141 62',
 '82 1436 142 37 2085 2091:2864:44 139 147 600 986 948',
 '65 34:814:391 423',
 '1655 2364 8:1880:1357 464 59',
 '1739 965 9:497:55 413 29',
 '1426 7:1193:1182 11',
 '1467 7:1017:975 42',
 '1682 3 2105:2988:15 14 2959',
 '1631 1591 1773 442 46 101 14:1696:48 21 63 661 220 389 294',
 '34 1599:203:47 156',
 '2514 441 1394 1975 34:7459:261 451 234 6419 94',
 '34 105:593:282 311',
 '425 37 1704:1350:543 800 7',
 '1941 14 693:1566:1065 42 459',
 '175 34:486:63 423',
 '2189 4:101:80 21',
 '1210 9:958:929 29',
 '63 51 2 208:2075:196 216 45 1618',
 '434 188 37:2260:1618 442 200',
 '1652 2:700:681 19',
 '1446 1359 462 34:1933:468 115 1162 188',
 '90 6 78:900:802 32 66',
 '79 1705 34:193:22 30 141',
 '47 2416 3:160:73 80 7',
 '535 7:698:677 21',
 '457 14 2137 104 1655:2459:108 84 80 248 1939',
 '1743 37 619:1447:27 200 1220',
 '1802 525 34:304:63 194 47',
 '1697 3 118:182:8 7 167',
 '8 325:568:29 539',
 '1465 37:415:215 200',
 '1468 1442 52 2:678:102 354 216 6',
 '7 1687 440 2507 432:431:42 22 108 14 245',
 '7 11:40:11 29',
 '1756 739 3:962:159 789 14',
 '7 487 455:1298:11 58 1229',
 '14 532 44:2051:84 839 1128',
 '76 1698 8:234:21 7 206',
 '1520 1358 7:659:605 43 11',
 '1677 1191 1999 3 1601 1500:799:10 392 147 14 173 63',
 '53 14:1032:990 42',
 '7 2493:123:74 49',
 '1803 3:84:63 21',
 '410 1509 59 8:2421:1737 502 153 29',
 '6 469:559:74 485',
 '1444 103 503 7 67:1155:373 124 548 85 25',
 '1760 6:277:256 21',
 '1517 6:475:433 42',
 '34 637 657 25 1753:1884:329 561 322 432 240',
 '730 1769 1461 7:308:73 37 166 32',
 '9 618:459:59 400',
 '114 80 2148 6:1705:1170 22 481 32',
 '377 417 34 1678:1387:971 324 47 45',
 '7 441 1367 130:864:32 676 58 98',
 '1632 4:30:19 11',
 '3 1613:277:7 270',
 '680 1601 1659 7:1673:188 173 1217 95',
 '1206 576 6:19010:7302 11697 11',
 '1422 8:635:488 147',
 '1739 2 1567 1715 189:407:27 13 260 38 69',
 '177 8:286:139 147',
 '1498 1574 7 441:785:324 162 74 225',
 '1522 67 2512 1748 9 1810:2526:2033 38 87 292 29 47',
 '596 2 1669:279:254 6 19',
 '585 889 449 1426 8 2181:2957:341 25 1697 394 118 382',
 '144 1500 9 1415:1436:147 126 29 1134',
 '1616 9:90:31 59',
 '1374 3:38:24 14',
 '452 295 3:367:216 137 14',
 '25 1619 7:259:216 32 11',
 '34 1594:62:47 15',
 '428 1999 421 2:6674:4536 98 2027 13',
 '727 14:431:305 126',
 '1817 9:198:110 88',
 '3 2513 1775 1673 41:754:7 522 84 16 125',
 '1922 1762 6:1013:971 31 11',
 '55 2 1627:610:594 6 10',
 '1458 403 2:619:216 378 25',
 '1399 6:60:18 42',
 '1647 1507 6:1034:292 721 21',
 '416 447 4:2726:2592 113 21',
 '1595 6 1626 296:747:31 42 293 381',
 '1052 1569 1592 2:3044:2516 484 19 25',
 '37 1661:1406:1401 5',
 '4 2499 369:1225:11 81 1133',
 '1258 9:98:39 59',
 '56 2 418:514:198 51 265',
 '504 443 2:2491:581 1885 25',
 '1750 34 2492 1767:486:73 235 49 129',
 '1755 3:114:64 50',
 '37 2072:1541:1401 140',
 '183 1265 6 1629 1496 1732:417:59 103 11 10 156 78',
 '9 1469:736:88 648',
 '433 182 185 1760 1522 14 1694:3443:2592 129 113 51 254 294 10',
 '452 366 1619 4 531:1703:323 819 65 42 454',
 '1629 1705 14:87:15 30 42',
 '1693 7 1436:199:7 53 139',
 '1665 4:16:5 11',
 '2512 8 1636:240:174 59 7',
 '1600 1503 426 34:3273:219 1453 1225 376',
 '1436 1078 7:978:279 678 21',
 '202 4:1521:1489 32',
 '141 474 444 8:2589:1176 96 1229 88',
 '1485 34:295:248 47',
 '1497 7:309:288 21',
 '1718 9 103 18 987:876:38 29 497 178 134',
 '463 9:1330:1242 88',
 '1699 34 1449:1154:15 329 810',
 '1624 90 396 8:3143:586 702 1737 118',
 '1761 4:100:79 21',
 '1690 1216 14:521:102 335 84',
 '362 605 2514 446 1450 181 37:3928:1737 307 608 431 166 279 400',
 '1389 14:291:39 252',
 '57 57 1012 405 1571 1386 7:2451:153 76 428 1510 215 58 11',
 '1517 1643 417 1775 452 6:3058:1154 31 1618 126 108 21',
 '1207 8 1769:1100:1016 29 55',
 '322 438 3:1249:598 615 36',
 '1266 2:30:24 6',
 '4 1360:210:21 189',
 '1666 445 1619 34:1527:34 1208 97 188',
 '844 336 1638 2:2292:13 2265 8 6',
 '815 2489 7:45:5 29 11',
 '708 757 9:150:76 15 59',
 '1986 1776 1204 8 103 1248:3773:343 42 3210 29 124 25',
 '452 14:365:323 42',
 '438 1576 1317 720 9:2850:2458 45 13 158 176',
 '151 8:1614:1585 29',
 '1701 419 1657 459 1195 7:1945:17 181 194 397 1061 95',
 '2490 2206 14:1466:22 1276 168',
 '1915 34:2187:2140 47',
 '601 14 1118:2438:1133 42 1263',
 '1612 1997 991 511 34 1584:1367:486 97 538 194 47 5',
 '89 436 102 4 1687 342:2411:100 904 62 32 19 1294',
 '1640 455 1070 562 37 1359:5799:15 4302 169 427 800 86',
 '2453 7 2517:67:44 21 2',
 '112 859 1605 1376 14 1680:979:167 129 388 166 126 3',
 '9 553 1322:3651:235 3398 18']

In [93]:
#save db_utility_data to file
with open('db_utility_data.txt', 'w') as f:
    for item in db_utility_data:
        f.write("%s\n" % item)